# Generated by Django 6.0.7 on 2026-07-21 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('programme_area', models.CharField(choices=[('entrepreneurship', 'Entrepreneurship & Business Growth'), ('leadership', 'Executive, Leadership & Management'), ('workplace', 'Workplace Learning & Professional Growth'), ('ai_strategy', 'AI Strategy for Senior Leaders'), ('womens_leadership', "Women's Leadership Development")], max_length=50)),
                ('level', models.CharField(choices=[('foundational', 'Foundational (Micro-Entrepreneurs)'), ('intermediate', 'Intermediate (SME Managers)'), ('advanced', 'Advanced (Senior Leaders)')], max_length=20)),
                ('skills_taught', models.JSONField(default=list, help_text='List of skill tags')),
                ('duration_mins', models.IntegerField()),
                ('prerequisites', models.JSONField(default=list, help_text='List of prerequisite course_ids')),
                ('is_paid', models.BooleanField(default=False, help_text='Paid certificate vs free access')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('micro_business_owner', 'Micro-Business Owner'), ('sme_manager', 'SME Manager'), ('corporate_employee', 'Corporate Employee'), ('senior_executive', 'Senior Executive')], max_length=50)),
                ('industry', models.CharField(choices=[('retail', 'Retail'), ('agriculture', 'Agriculture'), ('financial_services', 'Financial Services'), ('manufacturing', 'Manufacturing'), ('professional_services', 'Professional Services'), ('ngo_development', 'NGO/Development'), ('technology', 'Technology'), ('hospitality', 'Hospitality')], max_length=50)),
                ('company_size', models.CharField(choices=[('micro', 'Micro (1-10 employees)'), ('small', 'Small (11-50 employees)'), ('medium', 'Medium (51-250 employees)'), ('large', 'Large (251+ employees)')], max_length=20)),
                ('seniority', models.CharField(max_length=50)),
                ('stated_goal', models.TextField(help_text='Outcome-oriented goal statement')),
                ('true_interest', models.CharField(blank=True, help_text='Hidden variable for synthetic data generation only', max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='survey', serialize=False, to='ami_course_recommendations.user')),
                ('skill_gaps', models.JSONField(default=list, help_text='List of skill gap tags')),
                ('goals', models.JSONField(default=list, help_text='List of goal tags')),
                ('preferred_topics', models.JSONField(default=list, help_text='List of topic preference tags')),
                ('confidence_by_topic', models.JSONField(default=dict, help_text='Dict of topic -> confidence score (1-5)')),
            ],
            options={
                'db_table': 'survey_responses',
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('dropped', 'Dropped')], max_length=20)),
                ('progress_pct', models.FloatField(help_text='0-100')),
                ('quiz_score', models.FloatField(blank=True, help_text='0-100, null if not completed', null=True)),
                ('timestamp', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='ami_course_recommendations.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='ami_course_recommendations.user')),
            ],
            options={
                'db_table': 'usage_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='usage_event_user_id_3c90f8_idx'), models.Index(fields=['course', 'event_type'], name='usage_event_course__8d7332_idx')],
            },
        ),
    ]
