"""
Explainability layer for course recommendations.

Converts an AggregatedScore into a human-readable reason string that the
AI coach bot can surface directly to the learner. The reason is templated
off the highest-contributing scoring component, not generated by an LLM.

Why templated strings rather than LLM:
- Deterministic: the same inputs always produce the same reason
- Auditable: AMI reports verified 86% business-performance improvement to
  funders; "LLM-generated reason" is not a defensible source for that claim
- Debuggable: every reason traces back to a specific scorer + data point
- Fast: no API latency or token cost at inference time
- An LLM could wrap these reasons in a warmer coaching tone as a bonus step
  (see WRITEUP.md), but the underlying logic must remain auditable

Reason template selection:
- Determined by which of the three components contributes most to final_score
- Reflects AMI's 70/20/10 ethos where possible: usage-driven reasons emphasise
  practical application; survey-driven reasons emphasise stated intent
- Falls back gracefully through a priority chain so every user gets a reason

Template patterns (matching DESIGN.md examples):
  Survey-led:  "Because you told us you want to improve {goal}, we suggest {title}"
  Usage-led:   "Because you completed {prior_title}, {title} is a natural next step"
  Context-led: "Well-suited for {seniority}s in {industry} looking to {goal_fragment}"
  Cohort-led:  "Popular with {role}s in {industry} at a similar stage"
  Cold-start:  "A strong starting point for {seniority}s focused on {goal_fragment}"
"""

from dataclasses import dataclass
from ami_course_recommendations.models import User, Course, UsageEvent
from engine.coldstart import AggregatedScore
from engine import llm


# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class RecommendationReason:
    """
    Structured reason for a single recommendation.

    Attributes:
        short:  One sentence suitable for a list view or notification
        detail: Slightly longer version with more context, for a detail panel
        driver: Which signal drove this recommendation ('survey', 'usage',
                'context', 'cohort', or 'fallback') — useful for A/B analysis
    """
    short: str
    detail: str
    driver: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _goal_fragment(user: User) -> str:
    """
    Extract a short goal phrase from the user's stated_goal or survey.
    Falls back to a role-appropriate generic if nothing is set.
    """
    if user.stated_goal:
        # Trim very long goals to a readable fragment
        goal = user.stated_goal
        if len(goal) > 60:
            # Keep up to the first clause
            for sep in [",", " and ", " so ", " to "]:
                if sep in goal[:60]:
                    return goal[:goal.index(sep, 0, 60)].strip().lower()
        return goal.lower()

    role_fallbacks = {
        "micro_business_owner": "grow your business",
        "sme_manager": "build your management skills",
        "corporate_employee": "advance your career",
        "senior_executive": "lead more effectively",
    }
    return role_fallbacks.get(user.role, "develop your skills")


def _get_best_prior_course_title(user: User, course: Course) -> str | None:
    """
    Return the title of the completed course most similar to the candidate,
    used to build usage-driven reason strings.
    Excludes the candidate course itself to avoid circular reasons.
    """
    completed_events = UsageEvent.objects.filter(
        user=user,
        event_type="completed",
        progress_pct__gte=80,
    ).select_related("course")

    course_tags = set(s.lower() for s in course.skills_taught)
    best_overlap = 0.0
    best_title = None

    for event in completed_events:
        if not event.quiz_score or event.quiz_score < 60:
            continue
        # Never say "because you completed X, we suggest X"
        if event.course.course_id == course.course_id:
            continue
        prior_tags = set(s.lower() for s in event.course.skills_taught)
        if not prior_tags:
            continue
        overlap = len(course_tags & prior_tags) / len(course_tags | prior_tags)
        if overlap > best_overlap:
            best_overlap = overlap
            best_title = event.course.title

    return best_title if best_overlap > 0.15 else None


def _get_primary_survey_tag(user: User, course: Course) -> str | None:
    """
    Return the most prominent survey tag that overlaps with course skills,
    preferring goals > skill_gaps > preferred_topics.
    """
    try:
        survey = user.survey
    except Exception:
        return None

    course_tags = set(s.lower() for s in course.skills_taught)

    for tag_list in [survey.goals, survey.skill_gaps, survey.preferred_topics]:
        for tag in tag_list:
            if tag.lower() in course_tags:
                return tag

    return None


# ---------------------------------------------------------------------------
# Main builder
# ---------------------------------------------------------------------------

def build_reason(user: User, score: AggregatedScore) -> RecommendationReason:
    """
    Build a structured recommendation reason for a (user, course) pair.

    Selects the highest-contributing component from the score breakdown and
    applies the appropriate template. Falls back through a priority chain so
    every recommendation always has a reason.

    Args:
        user:  The learner receiving the recommendation
        score: AggregatedScore from aggregate_scores()

    Returns:
        RecommendationReason with short, detail, and driver fields
    """
    course = score.course
    goal = _goal_fragment(user)

    # Find highest-contributing scorer
    best = max(score.breakdown, key=lambda b: b.contribution, default=None)
    driver_name = best.name if best else "fallback"

    # ------------------------------------------------------------------ #
    # Survey-led reason                                                    #
    # ------------------------------------------------------------------ #
    if driver_name == "score_survey_match" and best.contribution > 0.01:
        survey_tag = _get_primary_survey_tag(user, course)

        if survey_tag:
            short = (
                f"Because you told us you want to improve {survey_tag}, "
                f"we suggest \"{course.title}\"."
            )
            detail = (
                f"Your survey identified {survey_tag} as a priority. "
                f"\"{course.title}\" covers exactly this — "
                f"it's a practical, hands-on module you can apply directly "
                f"to {goal}."
            )
            return RecommendationReason(short=short, detail=detail, driver="survey")

    # ------------------------------------------------------------------ #
    # Usage-led reason                                                     #
    # ------------------------------------------------------------------ #
    if driver_name == "score_usage_based" and best.contribution > 0.01:
        prior_title = _get_best_prior_course_title(user, course)

        if prior_title:
            short = (
                f"Because you completed \"{prior_title}\", "
                f"\"{course.title}\" is a natural next step."
            )
            detail = (
                f"Learners who completed \"{prior_title}\" and put those skills "
                f"into practice typically move on to \"{course.title}\" next. "
                f"It builds directly on what you've already done."
            )
            return RecommendationReason(short=short, detail=detail, driver="usage")

        # Cohort popularity (no personal prior — cold-start bridge)
        short = (
            f"\"{course.title}\" is popular with {user.role.replace('_', ' ')}s "
            f"in {user.industry.replace('_', ' ')} at a similar stage."
        )
        detail = (
            f"Other {user.role.replace('_', ' ')}s in {user.industry.replace('_', ' ')} "
            f"with goals similar to yours have found \"{course.title}\" "
            f"valuable for {goal}."
        )
        return RecommendationReason(short=short, detail=detail, driver="cohort")

    # ------------------------------------------------------------------ #
    # Work-context-led reason                                              #
    # ------------------------------------------------------------------ #
    if driver_name == "score_work_context" and best.contribution > 0.01:
        seniority_label = user.seniority.replace("-", " ")
        industry_label = user.industry.replace("_", " ")

        short = (
            f"Well-suited for {seniority_label}s in {industry_label} "
            f"looking to {goal}."
        )
        detail = (
            f"\"{course.title}\" is pitched at the right level for a "
            f"{seniority_label} in {industry_label}. "
            f"It addresses practical skills directly relevant to your context."
        )
        return RecommendationReason(short=short, detail=detail, driver="context")

    # ------------------------------------------------------------------ #
    # Fallback: used when user has no survey, no usage, and context is    #
    # weak — explicit about the signal source so the bot can be honest    #
    # ------------------------------------------------------------------ #
    seniority_label = user.seniority.replace("-", " ")
    short = (
        f"A strong starting point for {seniority_label}s "
        f"focused on {goal}."
    )
    detail = (
        f"\"{course.title}\" is one of the most practical modules available "
        f"for someone at your stage. Complete a few courses and we'll be able "
        f"to personalise recommendations much more closely."
    )
    return RecommendationReason(short=short, detail=detail, driver="fallback")


# ---------------------------------------------------------------------------
# Full recommendation object (used by API serializer)
# ---------------------------------------------------------------------------

@dataclass
class Recommendation:
    """
    A single ranked recommendation returned by the API.

    Positions are 1-indexed. All fields are JSON-serialisable primitives
    except course (serialised separately by the view layer).

    Fields:
        reason:          Templated reason string — deterministic and auditable.
        coaching_reason: Same content re-voiced in AMI's coaching tone by Groq.
                         Identical to reason when GROQ_API_KEY is not configured
                         or the API call fails, so callers always get a valid string.
    """
    position: int
    course: Course
    score: float
    usage_confidence: float
    reason: str
    reason_detail: str
    reason_driver: str
    score_breakdown: list[dict]
    coaching_reason: str   # Groq-enhanced version; falls back to reason


def build_recommendations(
    user: User,
    ranked_scores: list[AggregatedScore],
    n: int = 5,
) -> list[Recommendation]:
    """
    Convert a list of AggregatedScores into ranked Recommendation objects
    ready for API serialisation.

    Each recommendation carries two reason strings:
    - reason:          Deterministic template — always present, fully auditable.
    - coaching_reason: Groq-enhanced version in AMI's coaching voice. Falls back
                       to the templated reason if GROQ_API_KEY is absent or the
                       call fails. The coaching bot should display this field;
                       the audit trail should use reason.

    Args:
        user:          The learner receiving recommendations
        ranked_scores: Output of rank_courses(), already sorted descending
        n:             Number of recommendations to return

    Returns:
        List of Recommendation, length min(n, len(ranked_scores))
    """
    results = []

    for position, score in enumerate(ranked_scores[:n], start=1):
        reason_obj = build_reason(user, score)

        # Enhance the short reason with Groq coaching tone.
        # Pass the user's stated goal as context so Groq can personalise.
        coaching_reason = llm.enhance_reason(
            templated_reason=reason_obj.short,
            context=user.stated_goal if user.stated_goal else None,
        )

        breakdown = [
            {
                "component": b.name.replace("score_", ""),
                "raw_score": round(b.raw_score, 4),
                "effective_weight": round(b.effective_weight, 4),
                "contribution": round(b.contribution, 4),
            }
            for b in score.breakdown
        ]

        results.append(Recommendation(
            position=position,
            course=score.course,
            score=score.final_score,
            usage_confidence=score.usage_confidence,
            reason=reason_obj.short,
            reason_detail=reason_obj.detail,
            reason_driver=reason_obj.driver,
            score_breakdown=breakdown,
            coaching_reason=coaching_reason,
        ))

    return results
